version: "3"

services:
    db:
        image: mysql:8.0 
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./db:/var/lib/mysql
      
        
    web:
        build: 
            context: "."
            dockerfile: ./web.docker
        volumes: 
            - ./www:/var/www/html:rw
        ports: 
            - 8000:80
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports: 
            - 8001:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
        depends_on: 
            - db