version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./web:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports: 
          - 8081:80
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
      depends_on: 
          - db

  atacker:
      image: php:8-apache
      volumes: 
          - ./atacker_serwer:/var/www/html:rw
      ports: 
          - 8082:80
